// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXhSFHRSNoc7fZ_hV9OSn_RQ5KG8wnHdg',
    appId: '1:679796459336:web:87283fcb3c2954eb3a557d',
    messagingSenderId: '679796459336',
    projectId: 'aipodclips-8369c',
    authDomain: 'aipodclips-8369c.firebaseapp.com',
    storageBucket: 'aipodclips-8369c.firebasestorage.app',
    measurementId: 'G-Q43ZFBNYN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxTtEnjqRzrMX_iTXIqx-jYhpfFRrlcHI',
    appId: '1:679796459336:android:df060f459d64f16d3a557d',
    messagingSenderId: '679796459336',
    projectId: 'aipodclips-8369c',
    storageBucket: 'aipodclips-8369c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRCjt_Nwt3vPWoyhcKx12m8JU8r5wehw',
    appId: '1:679796459336:ios:5c3c58103adb5aec3a557d',
    messagingSenderId: '679796459336',
    projectId: 'aipodclips-8369c',
    storageBucket: 'aipodclips-8369c.firebasestorage.app',
    iosClientId: '679796459336-dfmib5r4q6rc4c0q3v1osl0m5nfgr5ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
